### ISSUE TITLE
Python error - 'no attribute 'transform'

### ISSUE THREAD

**Issue by cartochris** [lutraconsulting/qgis-discovery-plugin#7]
Hi there

I have set up the configuration to connect to my PostGIS address layer, I am able to search and retrieve autocomplete results, but on clicking an option I am getting a python error as follows:

location_geom.transform(transform)
AttributeError: 'NoneType' object has no attribute 'transform'

I think this is trying to see if the PostGIS layer has the same projection as my QGIS project, but it does so I am not too sure why I am getting this error?

Thanks

**Comment by wonder-sk** [comment]
What is type of geometry is stored in the table you are using? Are those just points or something else? 

Could you please verify that the chosen result row has valid (non-null) geometry?

If the geometry is non-null, could you please paste geometry's WKT representation here?

**Comment by cartochris** [comment]
Ah I have just downloaded QGIS 2.12 and tried it in there and it is working, if the plugin is only compatible from 2.12 onwards then my apologies!

**Comment by wonder-sk** [comment]
Hmm the plugin should work also with earlier QGIS versions. Which version did you use before?

Maybe if your geometry column contains more complex geometry type (e.g. geometry collection) then yes, only more recent QGIS versions can deal with those. But for ordinary geometries like point / linestring / polygon, things should work fine with QGIS 2.0 onwards...
